#################################################################################
# Copyright (c) 2022,2023 T-Systems International GmbH
# Copyright (c) 2022,2023 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License, Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0.
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
# SPDX-License-Identifier: Apache-2.0
################################################################################

ingress:
  enabled: true
  annotations:
    #kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  className: "nginx"
  host: "drs-pen.int.demo.catena-x.net"
  hosts:
    - host: drs-pen.int.demo.catena-x.net
      paths:
        - path: /
          pathType: ImplementationSpecific
          

  tls:
    enabled: true
    secretName: tls-secret
    host: "drs-pen.int.demo.catena-x.net"


# -- Pod resources requests and limits configuration
resources:
  limits:
    cpu: 200m
    memory: 300Mi
  requests:
    cpu: 200m
    memory: 300Mi


drs:
  secret:
    clientId: "<path:essential-services/data/daps#clientId>"
    clientSecret: "<path:essential-services/data/daps#clientSecret>"
    authServerUrl: "<path:essential-services/data/daps-register-svc-pen#auth-server-url>"
    realm: "<path:essential-services/data/daps-register-svc-pen#realm>"
    resource: "<path:essential-services/data/daps-register-svc-pen#resource>"
    apiUri: "<path:essential-services/data/daps-register-svc-pen#apiUri>"
    tokenUri: "<path:essential-services/data/daps-register-svc-pen#tokenUri>"
    jwkSetUri: "<path:essential-services/data/daps-register-svc-pen#jwk-set-uri>"
    

